runtime: python39
entrypoint: uvicorn main:api --host=0.0.0.0 --port=$PORT  

env_variables:
  MODEL_PATH: /ruta/al/modelo/modelo.pkl
  ENVIRONMENT: development

instance_class: F2  

automatic_scaling:
  target_cpu_utilization: 0.65  # Ajusta según tus necesidades

handlers:
- url: /.*
  script: auto